server:
  port: 9090

spring:
  application:
    name: notification-service
  mail:
    host: localhost
    port: 1025
  jms:
    servicebus:
      connection-string: "${azure_bus_key:}"
      pricing-tier: Standard
    listener:
      receive-timeout: 60000