server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/spring-microservices-security-realm

# Swagger OpenApi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls[0]:
      name: Product Service
      url: /aggregate/product-service/v3/api-docs
    urls[1]:
      name: Order Service
      url: /aggregate/order-service/v3/api-docs
    urls[2]:
      name: Inventory Service
      url: /aggregate/inventory-service/v3/api-docs

# Actuator Endpoints
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# Resilience4J Properties
resilience4j:
  # CircuitBreaker Properties
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 5
  # TimeLimiter Properties
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
  # Retry Properties
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s