server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: none
  jms:
    servicebus:
      connection-string: "${azure_bus_key:}"
      pricing-tier: Standard
    listener:
      receive-timeout: 60000

inventory:
  url: http://localhost:8083

springdoc:
  swagger-ui:
    path: /swagger-ui.html
