server:
  port: 8083

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:mem:inventorydb
    username: root
    password: root
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/